name: outpatient_mobile
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  get_storage:
  http: 1.2.1
  shared_preferences: ^2.0.8
  flutter_dotenv: ^5.0.2
  lottie: ^1.0.1
  introduction_screen: ^3.1.14
  carousel_slider: ^4.0.0
  buttons_tabbar: ^1.3.10
#  google_nav_bar: ^5.0.6
  image_picker: ^1.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/lottie/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf

